1
sophie-lamperg/Sprint_7 pull request #1
Opened 2023-01-24 14:37 UTC by sophie-lamperg

2023-01-24 14:38 UTC, sophie-lamperg commented
Привет! Пока что без отчета allure, жду ответа от наставника

2023-01-25 12:05 UTC, pavel-ulan requested changes
Неплохо. Работа аккуратная и тесты покрывают все требования. Но у тебя есть ряд неправильных подходов в методах, которые надо поправить. Посмотри комментарии пожалуйста. 
Так же, старайся всегда использовать пакеты и раскидывать классы по группам (модели в пакет моделей, классы с константами в пакет константы и т.п.)

2023-01-25 12:05 UTC, pavel-ulan commented on src/main/java/Api.java
> +    private final String URL = "https://qa-scooter.praktikum-services.ru/";
*надо исправить*
А для чего тебе privat константа с URI если ты ее не используешь (а опять задаешь URI в тестах)
Сделай ее паблик и используй или убери класс

2023-01-25 12:05 UTC, pavel-ulan commented on src/main/java/Courier.java
> +    public static Courier getRandomCourier() {
*можно лучше*
суть понятна, но технически курьер не рандомный (только логин) =)
ну и раз уж хардкодишь тестовые данные в таком методе, то лучше выноси их в константы класса. тогда если их надо использовать еще где-то, будет проще обратиться. а если надо поменять, то достаточно поменять только в одном месте.

2023-01-25 12:05 UTC, pavel-ulan commented on src/main/java/DeleteAndCreate.java
> +        Login login = new Login("alla", "1222");
*надо исправить*
а вот тут уже неприемлемо так делать. ты в утильный метод (создания/удаления) хардкодишь конкретного курьера. так не делается. если ты хочешь придерживаться такого подхода, то просто создай объект курьера и передавай в эти методы. Методы должны быть максимально абстрагированны от данных. Хардкод внутри утильных методов/ методов шагов и т.п. неприемлем

2023-01-25 12:05 UTC, pavel-ulan commented on src/main/java/DeleteAndCreate.java
> +        Login login = new Login("alla", "1222");
по сути твоя текущая реализация метода не работает, т.к. ты создаешь и тут же удаляешь курьера. а должна удалять тех, которые создаются в тестах

2023-01-25 12:16 UTC, pavel-ulan requested changes

2023-01-25 12:16 UTC, pavel-ulan commented on pom.xml
> +            <artifactId>testng</artifactId>
*надо исправить*
а для чего тебе testNG?

2023-01-25 12:26 UTC, pavel-ulan commented
К слову, а что не так с allure? Из того, что я вижу, у тебя неправильная конфигурация плагина в pom и много лишних зависимостей (чего только стоит использование 2х тестовых фреймворков testNG/junit)

2023-01-27 14:08 UTC, sophie-lamperg commented
Привет!
Не знаю, насколько успешно, но доработала проект.
Не понимаю в чем проблемы в тестах при логине (без пароля, например)

2023-01-30 13:00 UTC, pavel-ulan commented
Проблема не в тесте, проблема в названии теста. Используя в имени метода random ожидаешь рандомные данные, а у тебя только логин рандомный.

2023-01-30 13:17 UTC, pavel-ulan requested changes
почитай, что коммитят в репозиторий, а что нет. Можешь это проследить по тому, какие файлы заносят в .gitignore обычно (можешь поискать шаблоны файлов, в интернете много примеров под каждый из типов проектов. Например вот https://github.com/github/gitignore). Так например папку .idea и файлы iml в реп не коммитят.
У тебя все еще не происходит очистки данных, а after метод работает вхолостую.
Pom почистила - молодец =). Исправь еще очистку данных и будет отлично

2023-01-30 13:17 UTC, pavel-ulan commented on src/main/java/Constants.java
> +    protected final String expectedName = "alla";
*надо исправить*
Раз уж ты назвала класс Константы, то пусть они и будут константами. т.е. static и именоваться в UPPER_CASE.

2023-01-30 13:17 UTC, pavel-ulan commented on src/test/java/ListOrderTest.java
> +        MatcherAssert.assertThat("orders", notNullValue());
*можно лучше*
rest-assured позволяет делать assert многих видов (notNull в том числе), не обязательно было для этого использовать дополнительный matcher

2023-01-30 13:17 UTC, pavel-ulan commented on src/test/java/CreateCourierTest.java
> +        deleteAccount(id);
*надо исправить*
это всеравно не сработает. ты создаешь курьера в before, у тебя есть id поле класса, но после создания ты не присваиваешь ничего для id. Тем самым у тебя в after удаляется курьер с id==0 (что по сути неправильно, т.к. курьер был создан).
Добавь обработку в after "создавался ли курьер". А после создания достань id и положи в поле класса. Тогда это должно будет работать.

2023-01-31 12:35 UTC, sophie-lamperg commented
Привет! Сейчас все работает, отчет генерируется, надеюсь, что все ок :0

2023-02-01 14:13 UTC, pavel-ulan requested changes
Ты так и не справила очистку курьеров после тестов.

2023-02-01 14:13 UTC, pavel-ulan commented on src/test/java/CreateCourierTest.java
> +        deleteAccount(id);
эм, не вижу, что ты исправила эту проблему. если тебе что-то непонятно, напиши мне в пачке в личку что именно я попробую тебе ответить.

2023-02-01 14:13 UTC, pavel-ulan commented on src/test/java/CreateCourierTest.java
> +     //  CourierClient courierClient = new CourierClient();
*надо исправить*
молодец, что вынесла создание объекта из тестов. можно было кстати вынести вообще в поля класса, а не в before.
но не оставляй закоменченный код в работе.

2023-02-07 10:36 UTC, sophie-lamperg commented
Накостылила, но удаление теперь работает

2023-02-08 11:07 UTC, pavel-ulan approved these changes
Ок, не сказать, что ты все сделала на отлично, но ты проделала большую работу, молодец. С курьерами все же стоило бы доработать. Разберись пожалуйста по комментам которые я оставил и подумай как это можно было бы исправить.
Работу я зачту, но только в виде исключения и т.к. ты действительно проработала замечания с прошлых проверок (хоть и не полностью =) )

2023-02-08 11:07 UTC, pavel-ulan commented on Sprint_7.iml
> +</module>
*можно лучше**
iml файлы тоже в реп не коммитят

2023-02-08 11:07 UTC, pavel-ulan commented on src/main/java/OrderClient.java
> +public class OrderClient extends Constants {
**можно лучше**
смотри, константы, как правило, делаются паблик что бы иметь доступ из любой точки. В то же время это помогает не заботиться о наследовании класса констант.
Если надо экранирование, то как сделано у тебя - правильно.

2023-02-08 11:07 UTC, pavel-ulan commented on src/test/java/CreateCourierTest.java
> +        }
**можно лучше**
костыль, это здорово. но у тебя всеравно есть утечка. 
например для тестов где создается курьер (код ответа 200), этот курьер действительно будет удаляться.
но что будет происходить с курьером который создается в before? причем в тестах на ошибки и в положительных тестах картинка будет одинаковая, т.к. before работает для всех тестов

2023-02-08 11:07 UTC, pavel-ulan commented on src/test/java/LoginCourierTest.java
> +            }
**можно лучше**
тут конечно с курьером проще, но всеравно можно было бы сделать почище (например использовать id напрямую, а не передавать body).

2023-02-08 14:54 UTC, merged